spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: dhruvilrana
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    open-in-view: false
    ddl-auto : update
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: UTC

  data :
    redis:
      host : localhost
      port : 6379

server:
  port: 8081

jwt:
  secret: "pHnv7b6IZH3mFtiHBhdLo3GYB9LgNDByMAs5lruRlPw=" # BAES64 -> why $ does not come ?
  access-token-expiration: 900000       # 15 minutes (milliseconds)
  refresh-token-expiration: 604800000   # 7 days (milliseconds)