/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dhruvil.event;
@org.apache.avro.specific.AvroGenerated
public enum ApprovalGroupAction implements org.apache.avro.generic.GenericEnumSymbol<ApprovalGroupAction> {
  MEMBER_ADDED, MEMBER_REMOVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ApprovalGroupAction\",\"namespace\":\"com.dhruvil.event\",\"symbols\":[\"MEMBER_ADDED\",\"MEMBER_REMOVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
