/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dhruvil.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ApprovalGroupEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5565781836630758053L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApprovalGroupEvent\",\"namespace\":\"com.dhruvil.event\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"approvalGroupId\",\"type\":\"long\"},{\"name\":\"action\",\"type\":{\"type\":\"enum\",\"name\":\"ApprovalGroupAction\",\"symbols\":[\"MEMBER_ADDED\",\"MEMBER_REMOVED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApprovalGroupEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApprovalGroupEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ApprovalGroupEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ApprovalGroupEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ApprovalGroupEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ApprovalGroupEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ApprovalGroupEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ApprovalGroupEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ApprovalGroupEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long userId;
  private long approvalGroupId;
  private com.dhruvil.event.ApprovalGroupAction action;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApprovalGroupEvent() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param approvalGroupId The new value for approvalGroupId
   * @param action The new value for action
   */
  public ApprovalGroupEvent(java.lang.Long userId, java.lang.Long approvalGroupId, com.dhruvil.event.ApprovalGroupAction action) {
    this.userId = userId;
    this.approvalGroupId = approvalGroupId;
    this.action = action;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return approvalGroupId;
    case 2: return action;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: approvalGroupId = (java.lang.Long)value$; break;
    case 2: action = (com.dhruvil.event.ApprovalGroupAction)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'approvalGroupId' field.
   * @return The value of the 'approvalGroupId' field.
   */
  public long getApprovalGroupId() {
    return approvalGroupId;
  }


  /**
   * Sets the value of the 'approvalGroupId' field.
   * @param value the value to set.
   */
  public void setApprovalGroupId(long value) {
    this.approvalGroupId = value;
  }

  /**
   * Gets the value of the 'action' field.
   * @return The value of the 'action' field.
   */
  public com.dhruvil.event.ApprovalGroupAction getAction() {
    return action;
  }


  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(com.dhruvil.event.ApprovalGroupAction value) {
    this.action = value;
  }

  /**
   * Creates a new ApprovalGroupEvent RecordBuilder.
   * @return A new ApprovalGroupEvent RecordBuilder
   */
  public static com.dhruvil.event.ApprovalGroupEvent.Builder newBuilder() {
    return new com.dhruvil.event.ApprovalGroupEvent.Builder();
  }

  /**
   * Creates a new ApprovalGroupEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApprovalGroupEvent RecordBuilder
   */
  public static com.dhruvil.event.ApprovalGroupEvent.Builder newBuilder(com.dhruvil.event.ApprovalGroupEvent.Builder other) {
    if (other == null) {
      return new com.dhruvil.event.ApprovalGroupEvent.Builder();
    } else {
      return new com.dhruvil.event.ApprovalGroupEvent.Builder(other);
    }
  }

  /**
   * Creates a new ApprovalGroupEvent RecordBuilder by copying an existing ApprovalGroupEvent instance.
   * @param other The existing instance to copy.
   * @return A new ApprovalGroupEvent RecordBuilder
   */
  public static com.dhruvil.event.ApprovalGroupEvent.Builder newBuilder(com.dhruvil.event.ApprovalGroupEvent other) {
    if (other == null) {
      return new com.dhruvil.event.ApprovalGroupEvent.Builder();
    } else {
      return new com.dhruvil.event.ApprovalGroupEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ApprovalGroupEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApprovalGroupEvent>
    implements org.apache.avro.data.RecordBuilder<ApprovalGroupEvent> {

    private long userId;
    private long approvalGroupId;
    private com.dhruvil.event.ApprovalGroupAction action;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dhruvil.event.ApprovalGroupEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.approvalGroupId)) {
        this.approvalGroupId = data().deepCopy(fields()[1].schema(), other.approvalGroupId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.action)) {
        this.action = data().deepCopy(fields()[2].schema(), other.action);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ApprovalGroupEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dhruvil.event.ApprovalGroupEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.approvalGroupId)) {
        this.approvalGroupId = data().deepCopy(fields()[1].schema(), other.approvalGroupId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.action)) {
        this.action = data().deepCopy(fields()[2].schema(), other.action);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'approvalGroupId' field.
      * @return The value.
      */
    public long getApprovalGroupId() {
      return approvalGroupId;
    }


    /**
      * Sets the value of the 'approvalGroupId' field.
      * @param value The value of 'approvalGroupId'.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder setApprovalGroupId(long value) {
      validate(fields()[1], value);
      this.approvalGroupId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'approvalGroupId' field has been set.
      * @return True if the 'approvalGroupId' field has been set, false otherwise.
      */
    public boolean hasApprovalGroupId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'approvalGroupId' field.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder clearApprovalGroupId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'action' field.
      * @return The value.
      */
    public com.dhruvil.event.ApprovalGroupAction getAction() {
      return action;
    }


    /**
      * Sets the value of the 'action' field.
      * @param value The value of 'action'.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder setAction(com.dhruvil.event.ApprovalGroupAction value) {
      validate(fields()[2], value);
      this.action = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'action' field has been set.
      * @return True if the 'action' field has been set, false otherwise.
      */
    public boolean hasAction() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'action' field.
      * @return This builder.
      */
    public com.dhruvil.event.ApprovalGroupEvent.Builder clearAction() {
      action = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApprovalGroupEvent build() {
      try {
        ApprovalGroupEvent record = new ApprovalGroupEvent();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.approvalGroupId = fieldSetFlags()[1] ? this.approvalGroupId : (java.lang.Long) defaultValue(fields()[1]);
        record.action = fieldSetFlags()[2] ? this.action : (com.dhruvil.event.ApprovalGroupAction) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApprovalGroupEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApprovalGroupEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApprovalGroupEvent>
    READER$ = (org.apache.avro.io.DatumReader<ApprovalGroupEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeLong(this.approvalGroupId);

    out.writeEnum(this.action.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.approvalGroupId = in.readLong();

      this.action = com.dhruvil.event.ApprovalGroupAction.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.approvalGroupId = in.readLong();
          break;

        case 2:
          this.action = com.dhruvil.event.ApprovalGroupAction.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }

  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + Long.hashCode(userId);
    result = 31 * result + Long.hashCode(approvalGroupId);
    result = 31 * result + (action == null ? 0 : ((java.lang.Enum) action).ordinal());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ApprovalGroupEvent)) {
      return false;
    }
    ApprovalGroupEvent other = (ApprovalGroupEvent) o;
    if (this.userId != other.userId) {
      return false;
    }
    if (this.approvalGroupId != other.approvalGroupId) {
      return false;
    }
    if (!java.util.Objects.equals(this.action, other.action)) {
      return false;
    }
    return true;
  }
}










