spring:
  application:
    name: config-server
  cloud :
    config:
      server :
        git :
          uri : https://github.com/Dhruvil316/Access-Governance-Hub-Config-Server
          username : Dhruvil316
          password : ${GITHUB_TOKEN}
          default-label : main
server :
  port : 8888